### PR TITLE
User features(create account and login)

### PR DESCRIPTION
**Pull request by nadralia**
Please Kindly review and give feedback
@KengoWada @3Nakajugo @Anguandia @Araali1 @bakersen @bashirdeveloper @bekeplar @bisonlou @CandySusan @davicken @dtnnml @e-ian @erioc @ernesthenry @fionaharriet @Genza999 @HabibSentongo @HarrietAkot @HarunaIbnYusuf @JammyKalungi @jennizalwango @jkMugabe @joekirumira @k7ko @kabaliisa @KapsonLabs @kayongopique @kdenno @Kwandera @kyakusahmed @Kyeza @lizz24 @llwasampijja @LynetteMK @Manorlds-Eaglespark @masete @Mastula77 @MukuruH @mwes23 @nadralia @nanfuka @NANKYAPHIONA @natalie-abbie @noahkalyesubula @PatrickMugayaJoel @reifred @richien @ringtho @StephenCMwanika @v1b3m

### CODE REVIEW

**Comment by masete** [comment]
hey @nadralia i see your validations are in the same file as the views, i would idvise you isolate them

**Comment by bekeplar** [comment]
I just urge you to separate some of your scripts to work on with maintainability. Also work on coverage badge. Write more tests to cover the functionality of your project

**Comment by llwasampijja** [comment]
I noticed you coverage is unknown try installing pytest-cov and adding the command "--cov" at the end of the pytest line in .travis.yml instead of "/tests"

**Comment by llwasampijja** [comment]
Also  @nadralia I think the second "pip install coveralls" isn't necessary since coveralls is already installed from the "pip install -r requirements.txt" command

**Pull request merged**
